### ISSUE TITLE
Running the script gives this error:  File "\Spam-Botz-1.2.0\src\Spam_botz.py", line 13, in <module>     os.system('cls')

### ISSUE THREAD

**Issue by Jonybtw** [SVijayB/Spam-Botz#5]
I found the fix just import os library before "from os import system" like this: 

from Modules.Numbers import *
from Modules.RandNumbers import *
from Modules.Static import *
from Modules.RandomWords import *
from Modules.RageSpam import * 
from Modules.SentenceBreaker import *
from Modules.Colours import *
from time import sleep
import os
from os import system

**Comment by SVijayB** [comment]
Hey @Jonybtw thanks for letting me know. Fixed the error in beb877859126d6a5e5b5ed128742336fa0f0fd84.
